### PR TITLE
Use port 8000 instead of port 80

### PR DESCRIPTION
**Pull request by berezovskyi**
Issue #6

### CODE REVIEW

**Comment by berezovskyi** [comment]
Build fails due to #9, not due to the changes in this PR:

> Non-resolvable parent POM: Could not transfer artifact org.ldp4j:ldp4j-build:pom:0.2.0-SNAPSHOT

**Comment by mestebangutierrez** [comment]
I wondered if this would hit back at any point in time. There were some problems with the Sonatype OSSRH repository and some of our snapshot were removed unadvertedly.

**Comment by berezovskyi** [comment]
I think the default policy is to remove snapshot once the same version is released: https://support.sonatype.com/hc/en-us/articles/213465208-What-do-the-scheduled-tasks-in-Nexus-do-and-how-often-should-I-run-them-

So once 0.2.0 was released, 0.2.0-SNAPSHOT might have been deleted automatically.

**Comment by mestebangutierrez** [comment]
The point is that they do not provide any insight about the "Nexus configuration" used for their Snapshot repository (see the [guidelines they provide](http://central.sonatype.org/pages/ossrh-guide.html)).I filled in an issue in order to discover what happened to our lost snapshots and they told me about their SNAPSHOT remover task and their reason for it.

**Comment by mestebangutierrez** [comment]
'master' and 'develop' branches now use port 8080 for exposing the Frontend.

**Pull request closed without merging**
